pre-commit:
  parallel: true
  commands:
    fmt:
      run: task format
      stage_fixed: true
    lint:
      run: task lint:go
    actions:
      glob: ".github/workflows/*.{yml,yaml}"
      run: task lint:actions
    markdown:
      glob: "**/*.md"
      run: task lint:markdown
    test:
      run: gotestsum --format short-verbose -- -short ./...
    secrets:
      run: task secrets

commit-msg:
  commands:
    conventional:
      run: cog verify --file {1}
