version: "3"

tasks:
  default:
    silent: true
    cmd: task --list --sort alphanumeric

  bootstrap:
    desc: bootstrap local checkout for dev work
    cmds:
      - go mod download
      - lefthook install

  test:unit:
    desc: run unit tests
    cmd: gotestsum --format testname -- -race -skip '^TestCQL2AbstractTestSuite$' ./...

  test:ats:
    desc: run CQL2 Abstract Test Suite Gherkin tests
    cmd: gotestsum --format testname -- -race -run '^TestCQL2AbstractTestSuite$' ./...

  test:
    desc: run all test suites
    deps:
      - test:unit
      - test:ats

  format:
    desc: format source code
    cmds:
      - gofumpt -w .
      - goimports -w .

  lint:
    desc: run all linters
    deps:
      - lint:go
      - lint:markdown
      - lint:actions

  lint:actions:
    desc: run GitHub Actions workflow linter
    cmd: actionlint

  lint:go:
    desc: run Go linters with golangci-lint
    cmd: golangci-lint run ./...

  lint:markdown:
    desc: run Markdown linter
    cmd: markdownlint-cli2

  vulnerabilities:
    desc: check dependency vulnerabilities
    cmds:
      - govulncheck ./...
      - osv-scanner scan source .

  secrets:
    desc: check for secrets in code
    cmd: gitleaks dir

  check:
    desc: run all checks
    deps:
      - lint
      - test
